### PR TITLE
Option to hide tabs

### LINKED ISSUE #243: Move and hide tabs
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Why do you want this feature?

I want to move "Home" tab to the end
And hide "Playlists" tab

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Bnyro**
closes #243 
[not fully functional yet]

### CODE REVIEW

**Comment by z-huang** [comment]
The build yml file is causing trouble for PRs... I have to fix it.

**Comment by Bnyro** [comment]
> The build yml file is causing trouble for PRs... I have to fix it.

True, probably just check whether the environment variables are set and return otherwise :)

**Comment by z-huang** [comment]
Fixed.

**Comment by Bnyro** [comment]
Works now (at least in my tests).
I wasn't sure whether you have implemented a different way to set the value for preferences though, feel free to correct me there :)

**Comment by Bnyro** [comment]
By the way thanks for all your work spent on the project <3
I'm looking forward to go on contributing to the development in the future when I have more free time available :)

**Comment by z-huang** [comment]
I confirmed it works. The GitHub build action is just complaining some strings aren't translated in other languages - it doesn't matter.

**Pull request merged**
