### PR TITLE
Lock queue option and multi select

### PR DESCRIPTION
**Pull request by ruskcoder**
I split my old PR into two, and this one has these features. 

* Ability to lock queue swipe
* Long press on queue item to open menu
* Double press on queue item to favorite/like

### CODE REVIEW

**Comment by z-huang** [comment]
> Long press on queue item to open menu

This menu should be the same as `SongMenu`. You may notice the argument type difference between `Song` and `MediaMetadata`, so maybe you need to create a new compose function.

> Double press on queue item to favorite/like

I think this one is unnecessary. This should be in the song menu.

**Comment by ruskcoder** [comment]
I was trying to get it to work out, but to be able to check if a song is liked, it needs to have type `Song`, and sometimes converting mediaId to `Song` using the database returns null.

**Comment by ruskcoder** [comment]
@z-huang I tried quite a few things, but I was ultimately unable to get it to like/library because of the type mismatch. I was thinking instead of long press opening the `SongMenu` I could add the checkboxes feature mentioned in #1402

**Comment by ruskcoder** [comment]
@z-huang I finished the long press to select, and if you only select one the `SongMenu` will show, otherwise it will give you options for multiple selections. Check it out!

**Comment by ruskcoder** [comment]
Any updates? I don't want to keep this PR open too long clogging up space 😀

**Comment by z-huang** [comment]
Sorry, I'll take time to look at it.

**Comment by z-huang** [comment]
It will take some time because the code change is big. Second, I'm thinking about the UI design, e.g. should the function of long click be opening menu or entering multi-select mode.

**Comment by ruskcoder** [comment]
> It will take some time because the code change is big. Second, I'm thinking about the UI design, e.g. should the function of long click be opening menu or entering multi-select mode.

I mean, I think multi select mode is more intuitive. If you look at Google products like Google drive and Google files (I used those 2 as a reference), they use multi select mode for long click. But, if click the menu button with only one item selected, the Files/Drive will show a - different menu, which I have also implementing. 

So, at the end, the user has both options to use, single song menu, or multiple-select song menu depending on how many they select.

**Comment by z-huang** [comment]
I've done this feature by referring to this pr. Thanks for your contribution!

**Pull request closed without merging**
