### PR TITLE
Queue improvements

### PR DESCRIPTION
**Pull request by nvllz**
I messed up the whole thing in the first pull request, sorry.
This PR fixes the queue list display to show the currently playing song at the top of the list, which is very useful for large queues. I've also added a way to bring up the bottom menu when you long press on a queue item.

Short spotlight:
https://github.com/z-huang/InnerTune/assets/110673332/a99a4981-ce0e-417c-ae58-e00da24bac61

https://github.com/z-huang/InnerTune/issues/1067
https://github.com/z-huang/InnerTune/issues/1074

### CODE REVIEW

**Comment by nvllz** [comment]
Just added an option to lock queue order, which can be used to prevent changing song order. Also fixed #1111 bug in queue and playlist song lists (which appears to be a [Compose bug](https://issuetracker.google.com/issues/252334353)) with [this](https://gist.github.com/Joe3112/580d66f633c0f86c37e3f122092bf93e) modified code.

https://github.com/z-huang/InnerTune/assets/110673332/c6188fec-45df-4f95-b5f5-7d5ce8b3f48a

Also, the padlock and shuffle icons in the bottom bar of the queue list view are more visible with https://github.com/z-huang/InnerTune/pull/1173.

**Comment by netrunner-exe** [comment]
Hi @nvllz! You made some really useful and needed improvements and fixed bugs that were annoying me a bit, especially with the `SwipeToDismiss`, great job! I'm looking forward to these changes getting into the branch. I would like to ask you, perhaps you can bring back the track switching by swiping on the album cover. The previous implementation was a bit buggy and was removed, but it’s really missing. Thank you!

**Comment by nvllz** [comment]
Hi @netrunner-exe. Thanks for the kind words, it's not great yet I guess, but I tried my best. I may look into this album cover swiping in the future, but I can't promise anything yet.

**Comment by nvllz** [comment]
I edited the queue song menu handling so it doesn't have 'Start Radio' icon, which was referring to currently playing song instead of selected one. I would prefer to use SongMenu-like instance here, but don't know how to easily get `<Song>` from database. I can only pass mediaMetadata from Queue.kt, so getting  item from db with this data might change the way we can handle it.
If you, @z-huang have any idea how I could get this `<Song>` (so I could create a menu with `SongListItem(
        song = song,
        badges = {},
        trailingContent = {[...]`, which would not only look better but also give other options to make "play next", "add to library", heart icon in this menu), I could quickly make this menu look much better.

The most recent state of this menu looks like this:
4bbb63fd-0468-4bcf-966d-8671813c0d9e

**Comment by netrunner-exe** [comment]
> Hi @netrunner-exe. Thanks for the kind words, it's not great yet I guess, but I tried my best. I may look into this album cover swiping in the future, but I can't promise anything yet.

@nvllz, I compiled FOSS build from your branch today. I'll move on to using it daily and test it in general, but the already solved swipe bug makes me very happy :)

**Comment by nvllz** [comment]
Closing this PR as it certainly won't make the app in this form. I'll try to break it into smaller pieces of code.

**Pull request closed without merging**
