### PR TITLE
[French] Create strings.xml

### PR DESCRIPTION
**Pull request by kayoo123**
Addition of the French language

### CODE REVIEW

**Comment by z-huang** [comment]
Build failed. The directory name should be `values-fr-rFR` instead.

**Comment by kayoo123** [comment]
```
/home/runner/work/music/music/app/src/main/res/values-fr_FR: Error: Invalid resource directory name
```

I can't use underscore `_` for naming a directory  in android...

**Comment by z-huang** [comment]
image

Is the language for French or any region speaking French?

**Comment by z-huang** [comment]
Also, there are still some apostrophes not escaped.

**Comment by kayoo123** [comment]
> Is the language for French or any region speaking French?

It is only for France because each country who speak French language has some specificities that I do not know.

> Also, there are still some apostrophes not escaped.
> If you use Android Studio, it can show where needs to be fixed.
I'm not a developer, and I just use the github web IDE.
I'll try to get it into a CML-linter

**Comment by kayoo123** [comment]
xmllint.com told me that everything is good... 
I think I need deeper skills and use Android Studio to know where I'm wrong

**Comment by z-huang** [comment]
I'll just merge this PR first. Then modify in my computer to make lint check pass.

**Comment by z-huang** [comment]
Still one line needs to be added.

> (I'm sorry to give you so much work ^^ I just wanna help :p)

It's OK. I'll move the translation work to Crowdin after I come up with a distinct name for this app. In Crowdin, translation work will be easier.

**Comment by z-huang** [comment]
Great work!

**Pull request merged**
