### PR TITLE
Add yt-dlp fallback for stream extraction

### PR DESCRIPTION
**Pull request by gechoto**
This should fix the current playback issues: https://github.com/z-huang/InnerTune/issues/1748

This is not a perfect solution:
- it increases the apk size by a lot (includes python)
- it is slow
- is increases data usage (downloads the player js again and again for every stream)

But in my testing so far it works.
If you have a better idea feel free to share.

I tried to counter the slowness by only using this as a fallback for now.
In the long term it might be more reliable to offload more to yt-dlp.

I know the code is not the best. We can improve on that later.
However it should be fine for now as a quick fix.

Needs more testing.

TODO - before release:
_- disable sending login info when using IOS client (it does not support login anymore but results in an error)_ **DONE**

TODO - for later:
- maybe build split apks to decrease apk size
- see if there is a way to cache the player js to decrease data usage
- maybe update yt-dlp less often (daily + manual?) (currently every app start)
- check if the secure flag in the cookies file can be enabled
- maybe rename and optimize some stuff
- check if api_key can be removed from clients (it doesn't seem to be used anyone in recent clients?)
- check if TVHTML5 client can be removed

Note: This also contains a temporary change to set the cookie value to null if the user is logged out (because only null is considered logged-out). It can be removed after https://github.com/z-huang/InnerTune/pull/1694 is done.

### CODE REVIEW

**Comment by fishmodem** [comment]
Tried it and it works for non-age-restricted videos whether logged in or out, but it doesn't work for age restricted videos when logged in (or out, naturally). Gives "Unknown error." Unsure if it's the same error, i'll see if I can log it when I get home. 

Unrelated to this, but making the app actually display the error message instead of not giving any info would be great for an app that is subject to the whims of the yt api. I'll look into implementing a "See error details" button or something once this wave of blockage is resolved.

**Comment by gechoto** [comment]
> it doesn't work for age restricted videos when logged in

hm it should work
- which video are you testing with?
- does it work in the browser with the same account?

> making the app actually display the error message instead of not giving any info would be great

I agree the error messages should be improved at some point. I already added a `TODO` in the code for this.

**Comment by ThatOneCalculator** [comment]
Seems like #1772 may be a cleaner solution, especially in regards to the APK size

**Comment by gechoto** [comment]
> Seems like #1772 may be a cleaner solution, especially in regards to the APK size

I know about this PR and would prefer it. The problem is that it doesn't support login and things like volume normalization due to missing metadata.

To solve this I created a new PR which still supports login, has all metadata and keeps the app small and fast:
https://github.com/z-huang/InnerTune/pull/1774

**Comment by gechoto** [comment]
closing in favor of https://github.com/z-huang/InnerTune/pull/1774

**Pull request closed without merging**
