### PR TITLE
Added android auto local database search; also works with google assi…

### PR DESCRIPTION
**Pull request by scanetuk**
…stant voice search and "next", "stop", "start" etc voice controls working. Search results SQL will need more work as results ar a bit woolly at the moment.

### CODE REVIEW

**Comment by scanetuk** [comment]
All working ok, will probably need a re-write into your style. Cheers

**Comment by z-huang** [comment]
Thanks, please wait for my review.

**Comment by scanetuk** [comment]
Sorry thought I was creating another pull request for the miniplayer slider, hope it is ok, I find it is handy.

**Comment by z-huang** [comment]
> Sorry thought I was creating another pull request for the miniplayer slider, hope it is ok, I find it is handy.

Ah, I don't think this is a good idea. This makes mini player crowded. Please remove that.

**Comment by scanetuk** [comment]
Not sure if I have removed them correctly, i have deleted the files from the commit, I thought it looked a bit tight, I will have a think as very handy to skip through songs especially when going through a comunity playlist etc

**Comment by z-huang** [comment]
It's not removed.

**Comment by scanetuk** [comment]
Local copy got in a muddle so could not remove, have closed this pull request and can resubmit if you wish or you can take the bits you need to get the Android Auto search working. Thanks

**Pull request closed without merging**
