### PR TITLE
Disable colored bg tint in pure black mode setting

### PR DESCRIPTION
**Pull request by nvllz**
A toggle for turning off background tint in the Pure black theme.

https://github.com/z-huang/InnerTune/assets/110673332/6315d384-1f70-4165-bcfc-cdd023914b55

### CODE REVIEW

**Comment by netrunner-exe** [comment]
Hi @nvllz! Maybe you should also add this settings item (as well as other new notification texts, etc.) to` strings.xml` in other languages too (or automatically add new strings in other languages `strings.xml`), so that @z-huang doesn't have to do it manually and so that translators can better track changes and translate new options in time.

**Comment by nvllz** [comment]
Hi, once the owner makes a statement about my recent pull requests, I'll do the work if needed.

**Comment by Username1-a** [comment]
Looks great 👍

**Comment by Lurux** [comment]
Hey @nvllz, I think I'm willing to maintain a proper fork to collect your and other people's fixes while we wait for the owner to be active again - there are also some features I would like to add but I don't think would be added to the original project anyways.

What do you think ? I don't really know the etiquette, should I open an issue first or something ? Would you be willing to join forces with me ?

@z-huang would you be fine with that ? Do note whatever happens I intend to keep any major fixes neatly separated into branches to allow easier merging, like @nvllz has done up 'till now.

Anyways I don't really know what I'm doing so worst case scenario this will serve me as a playground to experiment and test ideas, but depending on your activity and the community's reaction this may or may not become a longer-term thing at some point.

**Comment by nvllz** [comment]
Hi. I don't know why the original maintainer hasn't commented on any of the recent PRs, although he has commented on some issue tickets. It took me some time to get these things done, and I tried my best to make my code as close to the current codebase as possible.

I've created a [separate branch](https://github.com/nvllz/InnerTune/tree/all_features) with all my commits, so you can build and test it yourself without much effort. Also feel free to merge my commits in your experimental fork if you like some.

As for maintaining a fork... idk. I'm not a developer myself, and I'd really like to see my efforts included in a next InnerTune update for all of you. There are some other fresh forks with https://github.com/BobbyESP/InnerTune having a promising start, so you can reach them and mention any not yet merged features from here. I think zhuang will take a stance on this matter soon, let's wait.

**Comment by Lurux** [comment]
Merged [here](https://github.com/Lurux/Concerto) while we wait for the author to be active again. Will simply bind it to the "pure black" setting, though.

**Comment by netrunner-exe** [comment]
> Merged [here](https://github.com/Lurux/Concerto) while we wait for the author to be active again. Will simply bind it to the "pure black" setting, though.

I think it's better when it's a separate option, as @nvllz intended, rather than a combined mode with pure black.

**Comment by Lurux** [comment]
"Pure black" is already a separate option from light and dark theme. So essentially we already have a three-state light/dark/black. I don't think it's useful to have a four-state light/dark/black-with-tint/black-without-tint.

I think a better way would be to have the no-tint bind to pure-black, but only un-tint page backgrounds, and not buttons and search bars - I need to look into that..

Anyways, we can continue to discuss [here](https://github.com/Lurux/Concerto/discussions/5) if you want, or we can stay here if you prefer.

**Comment by z-huang** [comment]
> Hi. I don't know why the original maintainer hasn't commented on any of the recent PRs, although he has commented on some issue tickets.

I got many issues and PRs when I was absent, so I need some time to tidy them up. But I'm happy that there're people making contribution to this project. I'll give more comments on this PR later.

**Comment by Lurux** [comment]
Should I continue with my fork or will you be able to merge things soon ?

**Comment by z-huang** [comment]
I will take a look at these PRs. Translation PRs will be accepted. As for feature PRs, I'll think more and decide whether they should be merged.

**Comment by Lurux** [comment]
Ok. I'm currently working on unifying the bottom menus, and want to make the artists pages accessible offline (although I don't know how to do that yet). I also have some other ides, but I'll see that depending on the time I have and your willingness to merge alternative ideas. I'll keep the fork around to work on it before submitting PRs.

**Comment by z-huang** [comment]
@nvllz I think disabling background tint makes the hierarchy of the elements less apparent. Users may be unclear about the boundaries between the components.

**Comment by nvllz** [comment]
@z-huang hey, good to see you again!
It's still just an option that might benefit those who use the app in the foreground for longer, especially with lyrics. If you can't do it due to low to no dialog border visibility, I'd still think about applying the black background to the player screen.

**Comment by z-huang** [comment]
Also, I think there're too much options to have "disable background tint" beside of "pure black", which may harm user experience...
I think a possible solution is to apply the black background only to the player screen and combine it into "pure black".

**Pull request closed without merging**
