### PR TITLE
Add possibility to change app startup sections

### PR DESCRIPTION
**Pull request by AndreVero**
Each section on the Home screen can be added or removed (link to the issue - https://github.com/z-huang/InnerTune/issues/1064)
Screenshot_20240811-104147
Screenshot_20240811-104203
Screenshot_20240811-104214
Screenshot_20240811-104222

### CODE REVIEW

**Comment by nvllz** [comment]
You can draw these switches with a "HOME SECTIONS" label, just like "PROXY" below.

**Comment by AndreVero** [comment]
> You can draw these switches with a "HOME SECTIONS" label, just like "PROXY" below.

Got you, I'll add a label as soon as possible.

**Comment by AndreVero** [comment]
> You can draw these switches with a "HOME SECTIONS" label, just like "PROXY" below.

@nvllz @z-huang Added the "Home sections" label

**Comment by z-huang** [comment]
If you disable all of these, your home screen will be empty. That doesn't look good.

**Comment by AndreVero** [comment]
@z-huang I thought it was exactly what some users want. But if it's breaking UI, maybe it's a good idea to leave only the possibility of removing new releases.

**Comment by AndreVero** [comment]
Or maybe an even better idea would be to add a label with something like "Enable sections in the Content settings"

**Comment by z-huang** [comment]
It's a UI/UX problem:

- Content settings page becomes crowded
- Home page becomes empty and tedious

What if I add more sections in home screen and make "new albums" and "mood and genres" at the bottom? And why do you want to hide these sections? Fetching the data just need very few internet traffics. If you don't want to see it, you can ignore them. YouTube Music and Spotify (and more!) don't have the option to let you hide something off, but people are okay with it. They just find what they want to use and see.

**Comment by AndreVero** [comment]
I've got you, it was just one of the open issues, so I took it. If now it's not needed - no problem.

**Comment by nvllz** [comment]
What about showing a dialog with 3 checkboxes? I mean if someone needs to tweak this screen, why not? I personally hate the new release albums and would use this feature to hide it.

**Comment by z-huang** [comment]
@nvllz Do you use quick picks?

**Comment by nvllz** [comment]
@z-huang Once in a while. Why?

**Comment by z-huang** [comment]
The home screen is revamped. New release and mood and genres are moved to the bottom. Are these settings still needed?

**Comment by z-huang** [comment]
Actually, I don't think it's needed. Closing.

**Pull request closed without merging**
