### PR TITLE
Support loading premium exclusive albums for premium accounts

### LINKED ISSUE #1630: Premium exclusive albums
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

An artist has albums which are not available without premium. Only logged-in premium users are able to see & play them.

Even when logged in with my premium account I still see only the free albums in InnerTune.
The app should make use of cookies from the logged-in session to get all the albums.

### Why do you want this feature?

I want to listen to all available albums. It is frustrating having no access to most albums from some artists.

### Additional information

I already tested adding a `setLogin = true` to this line:
https://github.com/z-huang/InnerTune/blob/ba3a3a0fe9d3499205a7fc91649938091cad75b8/innertube/src/main/java/com/zionhuang/innertube/YouTube.kt#L208

like this:
`val response = innerTube.browse(WEB_REMIX, browseId, setLogin = true).body<BrowseResponse>()`

and with it it does return all albums in the response (including the premium only ones) but for some reason the InnerTune GUI does not render any albums anymore after this change.
I'm not a great programmer so I don't know what is missing. But maybe this info helps as a starting point as it seems to go in the right direction.

### PR DESCRIPTION
**Pull request by gechoto**
This change makes premium-exclusive albums visible on artist pages - given the user is logged in and has an active music premium subscription

Fixes https://github.com/z-huang/InnerTune/issues/1630

### CODE REVIEW

**Comment by gechoto** [comment]
NOTE:
I couldn't test the function in `artistItemsContinuation` yet because the continuation is broken currently

For some reason you set `continuation = null` here:
https://github.com/z-huang/InnerTune/blob/ba3a3a0fe9d3499205a7fc91649938091cad75b8/innertube/src/main/java/com/zionhuang/innertube/YouTube.kt#L239

UPDATE: New PR is up fixing this: https://github.com/z-huang/InnerTune/pull/1637
Also tested the continuation with premium albums now. Works.

**Comment by gechoto** [comment]
Only downside is that we have to send the login cookie in more places so it makes it slightly worse for privacy.
However they already know what we listen to since we send the cookie with each player request anyways.
This only makes a difference in case someone opens an artist page but does not start listening to any song from them.

Note: for now the login cookie is not sent on search requests. This means that premium albums will not show in searches but only when opening artist pages.
This makes it a bit better privacy wise.

**Comment by gechoto** [comment]
I now added a toggle to the settings for this:


This is OFF by default.
This makes it better for privacy because users can turn it on only when needed.

@z-huang let me know what you think and if this is fine code wise

---

Btw. now that we have this toggle I could also try to add premium albums on search.

**Comment by gechoto** [comment]
I just added login support for searches. Also renamed the option:


Enabling this now uses the login cookie on artist pages and when using the search bar

**Comment by z-huang** [comment]
Once you're logged in your account, you don't have pure privacy. Therefore, I think we can send cookies as long as the api needs login information to respond more information or unlock some features. What do you think?

**Comment by gechoto** [comment]
> Once you're logged in your account, you don't have pure privacy.

I think we should still try to find a balance here. For most users it is not necessary to send the login cookie with every request so we should not force them to.
(Personally I also don't like it and disable it when I know it is not needed currently.)

Especially with the recent changes now YTM forces users to log in, see issues like these:
https://github.com/z-huang/InnerTune/issues/1614
https://github.com/z-huang/InnerTune/issues/1653

So I guess many users now log in only to avoid the playback issues.
All these users need is sending the cookie with the `player` request but nothing else.
I think it makes sense being able to limit the cookie usage to that to keep InnerTune still somewhat privacy focused at least as best as we can.



> What do you think?

I think this toggle is pretty cool and we should keep it.

Besides privacy another nice thing I noticed while using it the last few days:
YTM does not mark premium-only content. Once you are logged in you don't know anymore what content is free and what is premium exclusive.
Having this toggle helps me for example because I can quickly switch to a logged-out view to see what content is free and what I can share with my friends who don't have a premium subscription.

So yeah, good to have the option.

**Comment by gechoto** [comment]
Btw I now send the cookie on all browse request if the option is enabled.
This makes the code a bit simpler and I think it is more what people would expect when enabling such an option.

Also changed the description to reflect that:


@z-huang lmk if you have any more questions or feedback I should consider

**Comment by gechoto** [comment]
@z-huang I don't like to stress but unfortunately my premium runs out soon and I'm not sure yet if I will extend the subscription. If I can't get everything working that I need I might have to switch to a different streaming service and cancel premium for now. But this means I can't test anymore if anything comes up.

Not sure what is going on in your life but it would be cool to know approximately when you can review this. If you need a longer time it will be okay, I only want to know.

**Comment by z-huang** [comment]
I understand your concern. This PR looks okay, so I'll merge it right away. Is there anything else you need?

**Pull request merged**
