### PR TITLE
Added Malayalam (India) translations

### PR DESCRIPTION
**Pull request by aaj013**
- [x] Created Malayalam translation using Android studio based on README instructions.
- [x] Added all translations.
- [x] Successfully built apk and also run on phone.

Tried to change language and check if everything appearing correctly, but failed to do so. Only content language/region is being changed.
Device: Oneplus 8T(IN)
Android version: OOS12.1

### CODE REVIEW

**Comment by z-huang** [comment]
I can see your translation.
image

Thank you for having builded successfully before opening the PR. Therefore, I can merge your PR quickly.

**Comment by aaj013** [comment]
> I can see your translation. 

How to change the language? I found only option to change Content language and region. Is that the same? Am I missing this option because of Android version incompatibility? 
 
> Thank you for having builded successfully before opening the PR. Therefore, I can merge your PR quickly.

Always glad to help. :)

**Comment by z-huang** [comment]
> How to change the language?

Change it in Android settings.

**Comment by aaj013** [comment]
> Change it in Android settings.

Fine, will check it out. Still I would suggest an option within app to control the App language (may be an enhancement in future), just like in Newpipe. Default will be system language.

Screenshot_2022-09-29-11-55-08-65_ee8807d2de22f1831269d80920e33a3b

**Comment by z-huang** [comment]
It's a good idea. You can create an issue for that.

**Pull request merged**
