### PR TITLE
added bengali-bn translation

### PR DESCRIPTION
**Pull request by allubie**

### CODE REVIEW

**Comment by lucasmz-dev** [comment]
Would it be ok if this is imported into [our Weblate](https://hosted.weblate.org/projects/innertune/#languages)? Credits in Git should be kept.
There is a Bengali (India) translation already, if I was to merge it there, should it overwrite, or be separate? Even as separate, strings from here would fallback to regular Bengali, Android does that.

**Comment by allubie** [comment]
yeah sure you can import into weblate.
Bengali (India) is slightly different than Bengali (Bangladesh) if you can keep it separate.
@lucasmz-dev

**Comment by lucasmz-dev** [comment]
Forgot to do it before, but here:
https://hosted.weblate.org/projects/innertune/-/bn/ (there are a few untranslated strings you may want to do, also Fastlane)

https://github.com/z-huang/InnerTune/pull/1582/commits/a54c9359a20db012d0bd5bf35687df0ea4943bea

**Comment by lucasmz-dev** [comment]
There are quite a few [failing checks](https://hosted.weblate.org/translate/innertune/app/bn/?q=has:check) for Bengali, it's one of the languages that are not translated enough, and it can't fallback to the other Bengali on the Android side because that's also not translated; if they're not maintained enough they may be disabled or removed.

InnerTune is not active ATM but these translations are reused in other projects as well, such as OuterTune. In any case they'll never just be lost, so contributions are welcome! If you could help here that would be nice. It's hard to get contributors for these languages.

**Comment by lucasmz-dev** [comment]
Notably I'd be interested to know if the "same plurals" failing check is valid or not for this language. 
Plurals are still messy as translators often have to guess what the ones for their language is set up like, or don't know that they can add extra variants. Weblate deals with that but not when manually messing with files.

**Pull request closed without merging**
