### PR TITLE
Fix disconnection of the service when the activity dies

### PR DESCRIPTION
**Pull request by oguzsout**

### CODE REVIEW

**Comment by z-huang** [comment]
Can you explain this PR in more detail?

**Comment by oguzsout** [comment]
Even if you listen to the music from the application or pause and close it, the service runs in the background, so the music should stop when the application is closed, so the service should stop. I opened a fix pr because I saw this problem.

**Comment by ruskcoder** [comment]
I actually kind of like not patching this, many times I click close all, and that would stop my music 😅

**Comment by z-huang** [comment]
Yeah, that's why I didn't merge this PR directly. Some people may want to leave the music playing when they kill the app, while some may want to stop the music when they kill the app.

**Comment by dainvincible1** [comment]
> Yeah, that's why I didn't merge this PR directly. Some people may want to leave the music playing when they kill the app, while some may want to stop the music when they kill the app.

it will be better if there was a toggle. people can choose whatever they want themselves

**Comment by z-huang** [comment]
Thanks!

**Comment by z-huang** [comment]
Hi, I discovered a bug: play a song and change screen rotation, then the app crashed.
Log:
```
Caused by: java.lang.IllegalArgumentException: Service not registered: com.zionhuang.music.MainActivity$serviceConnection$1@16caba3
at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:2009)
at android.app.ContextImpl.unbindService(ContextImpl.java:2169)
at android.content.ContextWrapper.unbindService(ContextWrapper.java:925)
at com.zionhuang.music.MainActivity.onDestroy(MainActivity.kt:193)
```

Can you fix it? Thanks!

**Comment by oguzsout** [comment]
Hello, I think there is an improvement in [this pr](https://github.com/z-huang/InnerTune/pull/1462) related to the problem

**Pull request merged**
