### PR TITLE
Player slider movement animation and text transitions

### PR DESCRIPTION
**Pull request by nvllz**
https://github.com/user-attachments/assets/02d37a91-b021-438c-8a06-f170ac9354cf

 It looks much more natural than on the recording,

### CODE REVIEW

**Comment by z-huang** [comment]
I like the text animation, but not the slider movement. I want to know precise location when I drag the seek bar and don't want to wait for the dot to animate.

**Comment by z-huang** [comment]
If possible, transition for artwork will be great.

**Comment by nvllz** [comment]
@z-huang this wasn't the case as I managed the drag gesture to not wait for the slider (no animation), but tapping "next song" caused the animation to glitch, which made me drop the slider movement feature. But I kept the timer transition and added a fade to the miniplayer, as shown below.

https://github.com/user-attachments/assets/c31b24e6-eb13-4e16-b720-5752cee913de


As for the cover animation, I may try to implement it later in another PR, as it will require more work.

**Comment by z-huang** [comment]
I noticed a detail: the vertical position of texts may change if the two texts are of different size (e.g. English and Chinese). Can you fix it?

**Comment by nvllz** [comment]
Can't do much about it, as it seems to be a [compose bug](https://issuetracker.google.com/issues/240596679).

**Comment by nvllz** [comment]
Tomorrow I'll publish a more advanced PR with fixed animations for these labels containing certain characters.

**Pull request closed without merging**
