### PR TITLE
Player enhancement, flick up a little and it will slightly expanded version with more options and can use song position slider.

### PR DESCRIPTION
**Pull request by scanetuk**

### CODE REVIEW

**Comment by z-huang** [comment]
Can you attach a screen recording of your work? Thanks!

**Comment by scanetuk** [comment]
Here you go:
image

**Comment by z-huang** [comment]
I think it takes too much space. Not a simple UI design.

**Comment by scanetuk** [comment]
No worries, plz have a go to see what you think, I find it really it is really handy, the original one you have is still there as the initial player, flick up a bit and you get this one then flick up again and you get the full player.

**Pull request closed without merging**
