### PR TITLE
Icons enhancement

### PR DESCRIPTION
**Pull request by nvllz**
Replaced sharp icons with rounded ones, made icon state (filled/outlined) more consistent across different screens and menus.

Also changed icons for:
 - Sleep Timer
 - Multiple setting options
 - Text (filled if on, outline if not)

These changes are designed to make the app more elegant and modern, and to improve the user experience. If it gets merged, I'll definitely think about other changes to make the UI even better.

### CODE REVIEW

**Comment by nvllz** [comment]
Old vs new (different lyrics states here):
f74a6aa2-80a0-45b1-98c5-869589ae32d8

Some shot:

https://github.com/user-attachments/assets/c4acc891-9973-489f-b94d-2e1aef8030be

Playlist menu is now more user friendly:
08a0f9f4-eead-4bff-af10-1b0f5d5e16fa

**Comment by ruskcoder** [comment]
I think if you use an icon library, you can delete most of the drawables, and it will be a lot easier to change and add new icons.

**Comment by nvllz** [comment]
@ruskcoder I think that the icon library would load like thousands of icons and we would just use a friction of that here. I thought about it, and it took me some time to manually replace the icons, but it's not that hard. The main problem was the inconsistency, which means the app mixed some sharp shapes with clean, round icons. And some of the icons were filled, like randomly, so I made them outlines in menus (SongMenu, ArtistMenu), and filled for instances when user may want to take action (remove download, unlock padlock, delete from playlist).

ePNzSFuHopvSxj1bScsjsKbYiqvyD6We

**Comment by ruskcoder** [comment]
Tbh, I think filled icons everywhere looks quite a bit nicer than outlined icons. Just look at the radio icon! But, that Is just me.

**Comment by ruskcoder** [comment]
I'm just curious, what source do you use for these icons? Font awesome, fonts.google.com or something else?

**Comment by nvllz** [comment]
@z-huang is it okay now? I gave it a second thought and as people may be used to current style, let's stick to filled icons.

@ruskcoder Google Fonts.

**Comment by z-huang** [comment]
> Tbh, I think filled icons everywhere looks quite a bit nicer than outlined icons. Just look at the radio icon! But, that Is just me.

I agree with @ruskcoder. I'm used to current icons.

**Comment by z-huang** [comment]
> I think if you use an icon library, you can delete most of the drawables, and it will be a lot easier to change and add new icons.

`androidx.compose.material.icons.Icons` is an icon library, but it misses some icons.

**Comment by nvllz** [comment]
> I agree with @ruskcoder. I'm used to current icons.

@z-huang if you mean you prefer filled icons, I just put them back as before. Now it's just a change in some of icons, to make the design more consistent, as it was mixed with sharp and round icons before. I also tried to assign better matching icons to some settings. You may want to take a look at the [debug build](https://github.com/z-huang/InnerTune/actions/runs/10334537638).

**Comment by z-huang** [comment]
> > I agree with @ruskcoder. I'm used to current icons.
> 
> @z-huang if you mean you prefer filled icons, I just put them back as before. Now it's just a change in some of icons, to make the design more consistent, as it was mixed with sharp and round icons before. I also tried to assign better matching icons to some settings. You may want to take a look at the [debug build](https://github.com/z-huang/InnerTune/actions/runs/10334537638).

Ah, I can't start your apk. It just crashed whenever I started.

**Comment by nvllz** [comment]
@z-huang final version of this PR:

https://github.com/user-attachments/assets/fa3f41ba-1c77-43c1-97f3-ffc65eeff909

Idk what's wrong with that actions build tho.

**Comment by z-huang** [comment]
I updated some icons to yours. However, I prefer outlined style. (dfea7a0be0e45122213fe6f755799931e05d0f40)
This PR ends here, thanks for your contribution!

**Comment by nvllz** [comment]
Could you show which icons did you keep?

> I prefer outlined style

What does it even mean? Currently some icons are outdated material sharp icons (play, next/prev), and some are new, round - I spent a bit of time to make all the icons consistent, the same style. Do you really prefer a sharp play button with material 3 style? It looks just bad, give it a real thought.

**Comment by z-huang** [comment]
Material Symbols have three style: outline, rounded and sharp. I choose to use outline style, and your PR changes all icons to rounded style. Play, next and prev icons look the same as in https://fonts.google.com/icons?icon.size=24&icon.color=%235f6368&icon.platform=android&icon.style=Outlined . I don't mean rounded icons are ugly. They look great, too. But, changing icon styles is a big change in my point of view. It changes the way you feel with this app. So, I don't consider changing icon style currently. Maybe in the future.

**Comment by nvllz** [comment]
Man, I really understand your point. But since the app was recently revived, a lot of visual things have changed, and some changes need to be made. People are used to changes, and to be honest, this is not a big one, as you only get a few different icons, like the timer one (the only icon I hate). All the others are really the same as before, but rounded to fit in with all the other elements of the app, like the roundness of the cover, buttons, etc. I just think it's a good time to stick to the rounded style in the name of consistency.

I'm only doing this because it took me some time, and even if you plan to do the same thing in the future, it's just not worth wasting time on the same thing I just did here.

> Play, next and prev icons look the same as in [...]

Nah, it's a bit different (current vs round, don't mind outlined icons as I changed it later):

356753361-67e6b928-26a7-481b-b62b-66bfcfb4ec6c

**Comment by z-huang** [comment]
Sorry, maybe I will change icon style to rounded, but currently it's not the time. Best case: if Material Symbols have its library in the future, I may add an option in the settings to let user choose which icon set they like. I hope you can understand my prudence and concern. Nonetheless, I really appreciate your willingness to contribute to this project!

**Pull request closed without merging**
