### PR TITLE
Merge weblate backup

### PR DESCRIPTION
**Pull request by lucasmz-dev**
Things went wrong;
Should have all translations, but without Git madness
Weblate is locked in the meanwhile

### CODE REVIEW

**Comment by lucasmz-dev** [comment]
@z-huang This was definitely NOT intended. Remove Weblate's SSH access to the repo! I don't want to be able to mess with the repo directly before a PR. It should be a safe merge though, but definitely remove that.

**Comment by z-huang** [comment]
I removed Weblate bot from the collaborators. Surprised to know that Weblate bot has direct write permission. Maybe it was added by me very long ago.

**Comment by z-huang** [comment]
As a double-check, do I need to merge this PR?

**Comment by lucasmz-dev** [comment]
Now I got scared there, I thought I just deleted a bunch of commits from the GitHub oh my god I was about to throw myself out of a bridge

**Comment by lucasmz-dev** [comment]
We lost a few commits from like the stuff I added about translation info and such, it'd be nice to have those back

**Comment by lucasmz-dev** [comment]
@z-huang I'll try to create a PR for you that just returns to the same state as before

**Comment by z-huang** [comment]
> Now I got scared there, I thought I just deleted a bunch of commits from the GitHub oh my god I was about to throw myself out of a bridge

I removed the commits in this PR in `dev` by force-pushing.

**Comment by z-huang** [comment]
You can create a new PR and I'll merge it.

**Pull request merged**
