### PR TITLE
Translations update from Toolate

### PR DESCRIPTION
**Pull request by toolatebot**
Translations update from [Toolate](https://toolate.othing.xyz) for [InnerTune/InnerTune](https://toolate.othing.xyz/projects/innertune/innertune/).

It also includes following components:

* [InnerTune/metadata](https://toolate.othing.xyz/projects/innertune/metadata/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by yzqzss** [comment]
Locked. Until I figure out a way to make weblate respect empty lines. :(

sorry for the recent PR spam

**Comment by lucasmz-dev** [comment]
> Locked. Until I figure out a way to make weblate respect empty lines. :(
> 
> sorry for the recent PR spam

@yzqzss 
https://docs.weblate.org/en/weblate-5.6.2/admin/addons.html#addon-weblate-cleanup-blank ?

**Comment by z-huang** [comment]
Hi, the official Weblate translation platform has been set up. Please close the project in Toolate. Thanks for your contribution.

**Comment by yzqzss** [comment]
> Hi, the official Weblate translation platform has been set up. Please close the project in Toolate. Thanks for your contribution.

OK, deleted.

**Pull request closed without merging**
