### PR TITLE
Added Discord RPC!!

### PR DESCRIPTION
**Pull request by ruskcoder**
## I added Discord RPC support to InnerTune! 
image

There is a dedicated Discord Settings screen, where you can control all the options for the Discord RPC. 
image

With Artist Icon on:
image

With Artist Icon off:
image

You also can turn off the RPC when paused, just like Spotify. 

The album name is also displayed on the 3rd line, as either "On ${album}" or "Single"

### Feature Addons: 
I will add a time elapsed timer, 
And the Ability to add buttons to the RPC. 

### Known Issues: 
* When you spam pause/play, or you spam switching songs, the RPC may double so you have 3 concurrent RPCs for the same song, which will cause the RPC connection to close in a few seconds. 
* The issue stated above also occurs for the first song you play after opening the app. 

I will try to get bug fixes out asap.
Until then, enjoy :D !

### CODE REVIEW

**Comment by z-huang** [comment]
Wow! Thank in advance!

**Comment by ruskcoder** [comment]
That was quick!
I'll be working on the bugs, and they should be fixed by tomorrow at the same time.

**Comment by ruskcoder** [comment]
There might be a delay for a bit more, I am yet to find a solution to the bugs 😅. I'll reply when I have it figured out.

**Comment by z-huang** [comment]
That's okay! I'm trying to update gradle and dependencies at the moment.

**Comment by ruskcoder** [comment]
I just committed the final bug fix! There are 2 conflicts: app/build.gradle.kts and gradle/libs.versions.toml. 
For the build.gradle, the minSdk must be 27, as the dependency I use for the DiscordRPC (KizzyRPC) requires a minSdk of 27.

**Comment by ruskcoder** [comment]
I just added a new feature: Show App Name on RPC. Also, I had to disable the Show Artist Icon because the Piped API is down for some reason. I don't know if it is just my IP, but every time I go to the Piped API streams, it displays this error: 
    "message": "Got error: \"Sign in to confirm that you're not a bot\""
(URL: https://[pipedapi.r4fo.com/streams/dmteaIxE7DIo](https://pipedapi.r4fo.com/streams/dmteaIxE7DIo)

I need to use the Piped API to get the artist icon URL. 
There is a workaround, though, and that is to use InnerTube to provide the artistAvatar to the player through media metadata. But, I don't know how work with InnerTube and make it return the artistAvatar/uploaderAvatar.

**Comment by z-huang** [comment]
Reminder: please exclude output-metadata.json in your commit.

**Comment by ruskcoder** [comment]
> Reminder: please exclude output-metadata.json in your commit.

Yes, I just realized, and I will be removing it 😅

**Comment by ruskcoder** [comment]
I have completely finished everything planned for the DiscordRPC. It is ready to merge. And, when the Piped API does get fixed (or InnerTube fetches uploaderAvatar as well), then the show artist icon switch can be enabled again.

**Comment by z-huang** [comment]
When I press login, the webpage stucks. But when I go back, the account information is fetched. Does this also happen to you?

Update: I found the solution.

**Comment by z-huang** [comment]
Can we make the text shown in discord clickable and link to youtube?

**Comment by ruskcoder** [comment]
> Can we make the text shown in discord clickable and link to youtube?

Unfortunately, I tried that, it is only a Spotify feature. The progress bar is also only a Spotify feature. Discord does not allow anyone to do those other than Spotify.

**Comment by ruskcoder** [comment]
Instead of adding links, I added buttons that you can turn on to show the link.

**Comment by z-huang** [comment]
The buttons don't show. I tried [SpMp](https://github.com/toasterofbread/spmp) and its buttons don't show, too.

**Comment by z-huang** [comment]
What if a song has multiple artists? What do you plan to display the small image?

**Comment by ruskcoder** [comment]
> What if a song has multiple artists? What do you plan to display the small image?

The small image shows the uploader's profile picture, so whoever uploaded it to YouTube. When you hover over it, it also only shows the uploader's channel name.

**Comment by ruskcoder** [comment]
> The buttons don't show. I tried [SpMp](https://github.com/toasterofbread/spmp) and its buttons don't show, too.

For me, the buttons are showing.
I think the issue is if you look at your DiscordRPC with your account, it will not show the buttons.

image

But, if you look at the RPC from someone else's account or an alternate account, it works. 

image

**Comment by ruskcoder** [comment]
Also, Piped's API is very iffy, as it just stopped working once again. I think if you were able to return the uploader's channel name and avatar from InnerTube, we would not have to rely on Piped's API to show artist icon.

**Comment by ruskcoder** [comment]
Also, should I add a settings section where you can customize the text that is shown just like SpMp's customizable RPC text and Button text?

**Comment by z-huang** [comment]
I think we don't have to be so customizable as SpMp. Some toggles are enough. I'm reviewing the code and will make some commits.

**Comment by z-huang** [comment]
I noticed that whenever an update is needed for discord rpc, you close the current connection and start a new one. This is because KizzyRPC library doesn't support updating presence on the original connection. However, I tried [Kizzy](https://github.com/dead8309/Kizzy) and digged into the code. I found it does not use KizzyRPC but a rewritten version, which supports updating presence on the existing connection. Therefore, its latency is shorter. To achieve perfect experience, I may want to borrow the library to InnerTune.

You can take a look at these modules: https://github.com/dead8309/Kizzy/tree/master/data and https://github.com/dead8309/Kizzy/tree/master/gateway

**Comment by ruskcoder** [comment]
> I noticed that whenever an update is needed for discord rpc, you close the current connection and start a new one. This is because KizzyRPC library doesn't support updating presence on the original connection. However, I tried [Kizzy](https://github.com/dead8309/Kizzy) and digged into the code. I found it does not use KizzyRPC but a rewritten version, which supports updating presence on the existing connection. Therefore, its latency is shorter. To achieve perfect experience, I may want to borrow the library to InnerTune.
> 
> You can take a look at these modules: https://github.com/dead8309/Kizzy/tree/master/data and https://github.com/dead8309/Kizzy/tree/master/gateway

I was also looking at SpMp's code, and they have used the KizzyRPC library without closing the connection. It just creates a new connection and the old ones time out after a while. If you go to the activity list of the user, it will show a stack of all the unclosed RPC's. This will cause issues with the hide RPC on pause feature. 

I will write my own module/file using we sockets so it can be fully customisable and works as per the needs.

**Comment by z-huang** [comment]
Why not just using Kizzy's modules? It can reduce our time. Or, is there any feature you thought missing in Kizzy?

**Comment by ruskcoder** [comment]
> Why not just using Kizzy's modules? It can reduce our time. Or, is there any feature you thought missing in Kizzy?

That may be fine, but I think the Kizzy's modules contain extra code that may make sizes bigger unnecessarily. I think the code is also copyrighted. But, if that seems like the best option, we can go ahead with it.  

Also, I might be active less the following days, my semester is starting tomorrow and I will have to study for the upcoming assignments, but I should still be working time to time.

**Comment by z-huang** [comment]
Kizzy is licensed under GPL-3.0, same as InnerTune. I think it's okay to use the code directly if we preserve the copyright information in the code.

> Also, I might be active less the following days, my semester is starting tomorrow and I will have to study for the upcoming assignments, but I should still be working time to time.

That's fine! I'll do it if I have time, too.
By the way, it's very cool to have Discord RPC. This can also increase the popularity of InnerTune!

**Comment by z-huang** [comment]
I asked for the permission: https://github.com/dead8309/Kizzy/issues/276

**Comment by ruskcoder** [comment]
Thats perfect! I'll try to get started on the code, although I'll have to do a bit digging to learn to use the modules.

**Comment by ruskcoder** [comment]
It seems like almost all the modules are piggybacking off another, e.g. data has a source from domain and common, domain has a source from build-logic, etc...
Overall, I will be importing upto 4-5 modules just to add the RPC from kizzy. Instead, I will try to collect all essential files and create a module using just those.

**Comment by z-huang** [comment]
Actually, I almost finish this feature. I'll push it tomorrow.

**Comment by ruskcoder** [comment]
> Actually, I almost finish this feature. I'll push it tomorrow.

Should I wait until you finish to continue?

**Comment by owenconnorz** [comment]
Wow, nice work, guys! I was looking into YouTube Music sync for playlists, liked songs, etc., so I can use InnerTune across devices. Is anyone currently working on this, or can I look into doing it unless someone beats me to it? 🤣

**Comment by ruskcoder** [comment]
> Wow, nice work, guys! I was looking into YouTube Music sync for playlists, liked songs, etc., so I can use InnerTune across devices. Is anyone currently working on this, or can I look into doing it unless someone beats me to it? 🤣

I was gonna start that after all my current PR, using OurerTune's system as an example, which may take a while before I start. But if you are ready to work on it, go ahead!

**Comment by owenconnorz** [comment]
I just saw your version and am trying it out now. It seems awesome so far. Maybe I'll wait for you to add more features, since you basically have the code. 😉 But nice work, @ruskcoder The sync option is awesome. I can't wait for the Discord integration. Could you enable actions on your version for me to test, please? 😀

**Comment by ruskcoder** [comment]
> I just saw your version and am trying it out now. It seems awesome so far. Maybe I'll wait for you to add more features, since you basically have the code. 😉 But nice work, @ruskcoder The sync option is awesome. I can't wait for the Discord integration. Could you enable actions on your version for me to test, please? 😀

I've never used actions before, but I think I enabled them. lmk if it doesn't work.

**Comment by z-huang** [comment]
Done! 562065d05b02c9a807816b29c110cb0a6bab4bb1

**Comment by ruskcoder** [comment]
Shouldn't we show the album name on the RPC? I think it looks better.

**Comment by z-huang** [comment]
Album name and artist thumbnail are shown if available. Though I didn't actively fetch information if missing.

**Pull request closed without merging**
