### PR TITLE
Optional Buttons/Slider on queue

### PR DESCRIPTION
**Pull request by ruskcoder**
I added 2 features
1. Queue buttons
2. Queue Seek Bar

They can both be turned off in settings. 
The queue buttons can be either skip song, or skip 5 seconds. 

image
image
image

### CODE REVIEW

**Comment by ruskcoder** [comment]
I had finished the code for the seek bar, but unfortunately all my files were deleted when I forgot to commit and checked out to a different branch 😭. I will re-code it and complete the pr tomorrow.

**Comment by z-huang** [comment]
> I had finished the code for the seek bar, but unfortunately all my files were deleted when I forgot to commit and checked out to a different branch 😭. I will re-code it and complete the pr tomorrow.

So sad. 🥲 Actually, I'm not in favor of having player control buttons in queue screen. All these buttons can be done by clicking on the list items.

**Comment by nvllz** [comment]
@ruskcoder I think you should learn from my mistakes and not push multiple features with a single PR. I would recommend making each of these a separate request, would be easier to review and accept your changes as these control buttons are the blocker here I think.

**Comment by ruskcoder** [comment]
> > I had finished the code for the seek bar, but unfortunately all my files were deleted when I forgot to commit and checked out to a different branch 😭. I will re-code it and complete the pr tomorrow.
> 
> So sad. 🥲 Actually, I'm not in favor of having player control buttons in queue screen. All these buttons can be done by clicking on the list items.

One thing I liked was the skip 5 seconds, which can be useful from time to time. And I also added a settings option so anyone can turn it off. 

[

**Comment by ruskcoder** [comment]
> @ruskcoder I think you should learn from my mistakes and not push multiple features with a single PR. I would recommend making each of these a separate request, would be easier to review and accept your changes as these control buttons are the blocker here I think.

Yes, I took out the padlock from this one, and I will make a PR for just the padlock (and double-tap).

**Comment by ruskcoder** [comment]
Should I continue with this PR or close it? In my opinion a skip 5 seconds button will be useful, but it is fine if it isn't added.

**Comment by z-huang** [comment]
I think the lock is enough, sorry. Do you know that you can double click on the artwork to rewind or skip 5 seconds?

**Comment by ruskcoder** [comment]
> I think the lock is enough, sorry. Do you know that you can double click on the artwork to rewind or skip 5 seconds?

Oh! I never knew that! I will close this PR now.

**Pull request closed without merging**
