### PR TITLE
Translations update for ES language.

### PR DESCRIPTION
**Pull request by ItzHenry1**
Translation update for ES language

Added missing translations

### CODE REVIEW

**Comment by z-huang** [comment]
Build failed. There's something wrong in your pr. Please fix.

**Comment by ItzHenry1** [comment]
Fixed

**Comment by ItzHenry1** [comment]
> Build failed. There's something wrong in your pr. Please fix.

Fixed It, duplicated line was on the file

**Comment by z-huang** [comment]
Thanks!

**Pull request merged**
