### PR TITLE
Playlist menu improvements

### PR DESCRIPTION
**Pull request by nvllz**
A simple confirmation dialog before removing downloaded playlist. 
Related to https://github.com/z-huang/InnerTune/issues/1075

https://github.com/z-huang/InnerTune/assets/110673332/c8cb7722-7e14-43ac-83b2-b716b62727ea

### CODE REVIEW

**Comment by nvllz** [comment]
Added a confirmation dialog before deleting a playlist.

**Comment by owenconnorz** [comment]
> Added a confirmation dialog before deleting a playlist.

By any chance can you also do one for adding the same song into a playlist so we get promoted that the current song already exsist in playlist this would be grate to.

Also nice work mate

**Comment by nvllz** [comment]
Thank you. 
Unfortunately, making an ok/cancel dialog in this case would require a little more work because of the way the thing is handled. It would be easier to implement an "Ok" only dialog that says the song is already in the playlist, but I don't know if the community would like it that way, so you can only have one instance of a song in a playlist.

**Comment by owenconnorz** [comment]
No worries @nvllz thanks tho 😁

**Comment by nvllz** [comment]
I decided to put it here since this commit is somehow related to my recent work. I made a new version of PlaylistMenu that looks much better and matches other menus in the app. Also decided to put this little https://github.com/z-huang/InnerTune/pull/1176 PR here. It's the biggest I've done so far, and I really wish this along my other pull requests would get merged one day.

https://github.com/z-huang/InnerTune/assets/110673332/fcbc62b8-293f-40d5-86e8-da05af942412

**Comment by owencz1998** [comment]
Nice!! 

I would love to add made categories to the home page but I think that's a lot of work but would be nice for more.

**Comment by z-huang** [comment]
Thanks!

**Pull request merged**
