### PR TITLE
Some minor changes (v2)

### PR DESCRIPTION
**Pull request by JavkhlanK**
I just found out about this app, and it looks awesome! I decided to have a look at the codebase, and found some little warnings & changes I could fix/do.

Now on feature/innertube. til git branches can contain slashes btw.

### CODE REVIEW

**Comment by owencz1998** [comment]
Dude do u know how to fix this issue would be nice to be able to update without this 🤣

**Comment by JavkhlanK** [comment]
You'll have to uninstall the old version, then install that new APK.

**Comment by owencz1998** [comment]
Ahh ok it's just like other debug apps they allow me to just update it without having to remove I didn't know if there was a way to fix it 🙃

**Comment by z-huang** [comment]
Thanks!

**Pull request merged**
