### PR TITLE
Add support for sdk21, updated some versions

### PR DESCRIPTION
**Pull request by Osanosa**
This is my first pull request ever, so tell me if I fucked smth up

### CODE REVIEW

**Comment by Osanosa** [comment]
Looks like minification in release build breaks audio download, no idea how to fix it, prob will need some rule for ProGuard, mut without minification works fine

**Comment by ghost** [comment]
Why are we trying to support android 5.0 here (almost 10 years old) - sorry but I don't think implementing this makes sense. This is not a legacy app.
Or am I missing something :fearful:

**Comment by Osanosa** [comment]
Why not if compose is capable of? The only thing that's holding it is some
sort of converting Chinese character set and that's it. If this can be
simply disabled for outdated versions than it can run.

**Comment by z-huang** [comment]
According to statistics, very few people use Android 5.0. Not planned to support api 21.

**Pull request closed without merging**
